# 이중연결리스트(Double Linked List)
<font size=3> 이중연결리스트는 사실 하나의 노드의 하나의 링크인 거에서 <br>
하나의 노드에 두 개의 링크로 달라진 것밖에 없다. <br>
링크가 한 쪽 방향(이를테면 next)으로만 이어져있었다면,<br>
이중연결리스트는 next 뿐 아니라 prev 링크도 가지고 있다. </font>

In [4]:
#!/usr/bin/python

class Node:
    def __init__(self, data, next=None, prev=None): # prev매개변수가 추가되었다. 링크의 역할.
        self.data = data
        self.next = next
        self.prev = prev
    
def init_list():
    node_A = Node("A")
    node_B = Node("B")
    node_D = Node("D")
    node_E = Node("E")
    
    node_A.next = node_B
    node_B.next = node_D
    node_D.next = node_E
    node_B.prev = node_A
    node_D.prev = node_B
    node_E.prev = node_D
    return node_A
    
def print_list(node_A):
    node = node_A
    while node:
        print(node.data)
        node = node.next
    print()


In [14]:
if __name__ == '__main__':
    print("연결리스트 초기화 후")
    node_A = init_list()
    # print(node_A.data)
    print_list(node_A) # 그런데 희한한게 def 안에서 선언되었던 instances of class 들이 def. 가 실행이 종료되고 나서도 계속 살아있다는 거네? 
                       # 실체는 존재하지 않지만 (that is, the actual object has been gone.) 주소값과 그에 대한 정보들은 살아 있는건가
    

연결리스트 초기화 후
A
B
D
E



<font size=5> **이중연결리스트의 삽입알고리즘** </font> <br><br>
<font size=3> 앞서 **단일연결리스트**의 경우에는 노드를 새로 추가할 때, <br>
새로 추가하는 노드의 next를 먼저 잇고**(1)**, <br>
앞선 노드의 next(링크)를 새로 추가하는 노드와 연결시켰다**(2)**. (그리고 이 **순서는 매우 중요**하다고 했었다!) <br><br>
**_이중연결리스트_** 의 경우도 비슷하다. <br>
우선, **(1)**새로 추가하는 노드의 next(링크)를 먼저 잇고,<br>
**(2)**앞선 노드의 next(링크)를 새로 추가하는 노드와 연결시킨다.<br>
그리고, **(3)**새로 추가하는 노드의 prev(링크)를 앞선 노드와 연결시키고,<br>
**(4)**뒤따라오는 노드의 prev(링크)를 새로 추가하는 노드와 연결시킨다. </font>

In [41]:
# 4.1.2 이중연결리스트의 삽입 알고리즘
#!/usr/bin/python
class Node:
    def __init__(self, data, next=None, prev=None):
        self.data = data
        self.next = next
        self.prev = prev

def init_list():
    node_A = Node("A")
    node_B = Node("B")
    node_D = Node("D")
    node_E = Node("E")
    
    node_A.next = node_B
    node_B.next = node_D
    node_D.next = node_E
    node_B.prev = node_A
    node_D.prev = node_B
    node_E.prev = node_D
    return node_A

def delete_node(data, node_A):
    node = node_A
    
    #first
    if node.data == data:
        node.next.prev = None
        node_A = node.next
        del node
        return node_A
    
    else:
        node_H = node # 나중에 while문이 끝나고, return node_H 시작포인트로 쓸 것
        
    node = node.next
    while node:
        
        if node.data == data:
            # 근데 만약 지우려는 노드가 마지막 노드인 경우
            if node.next is None:
                node.prev.next = None
                print(f"맨 끝에 있는 {node.data} 노드데이터가 지워졌습니다.")
                del node
                break
                
            node.next.prev = node.prev
            node.prev.next = node.next
            print(f"{node.data} 노드 데이터가 지워졌습니다.")
            del node
            break
        
        node = node.next
        if node is None:
            print("The data you want to delete is not existed.")
            break
    
    
    return node_H
            

def insert_node(data, node_A):
    new_node = Node(data)
    node_P = node_A
    node_T = node_A
    while node_T.data <= data:
        node_P = node_T
        node_T = node_T.next
    
    new_node.next = node_T # 1) 새로 추가하는 노드의 next링크를 먼저 연결하고
    node_P.next = new_node # 2) 앞선 노드의 next링크를 새로 추가하는 노드에 연결하고
    new_node.prev = node_P # 3) 새로 추가하는 노드의 prev링크를 앞의 노드와 연결하고
    node_T.prev = new_node # 4) 뒤따라오는 노드의 prev링크를 새로 추가하는 노드와 연결한다.
                           # 결국 next, prev 링크 둘 다 새로 추가하는 노드를 기준으로 먼저 이루어진다.
def print_list(node_A):
    node = node_A
    while node:
        print(node.data)
        node = node.next
    print()
    

In [43]:
if __name__ == "__main__":
    print("연결 리스트 초기화 후")
    node_A = init_list()
    print_list(node_A)
    
    print("노드 C의 추가 후")
    insert_node("C", node_A)
    print_list(node_A)
    
    print("노드 마지막 E의 삭제 후")
    node_A = delete_node("E", node_A)
    print_list(node_A)
    

연결 리스트 초기화 후
A
B
D
E

노드 C의 추가 후
A
B
C
D
E

노드 마지막 E의 삭제 후
맨 끝에 있는 E 노드데이터가 지워졌습니다.
A
B
C
D



# Lesson 05 : 스택(Stack)과 큐(Queue)

In [44]:
#!/usr/bin/python

def push(item):
    stack.append(item)
    
def pop():
    return stack.pop()

In [49]:
if __name__ == "__main__":
    stack = []
    push(1)
    push(2)
    push(3)
    push(4)
    
    print("현재 stack의 모습")
    print(stack)
    
    while stack:
        print(f"POP > {pop():.1f}")

현재 stack의 모습
[1, 2, 3, 4]
POP > 4.0
POP > 3.0
POP > 2.0
POP > 1.0


## 스택(Stack)의 응용 : 계산기
<font size=3> 스택을 응용한 프로그램들은 굉장히 대단히 많지만, <br>
그 중에서 쉽게 구현할 수 있고 또 스택의 기능을 적나라하게 알아볼 수 있는 프로그램은 **계산기 프로그램**이다.

<font size=3> 이걸보자마자 **에이 너무 시시한거 아니냐**라고 말하는 지금의 당신.<br>
사실 *계산기 프로그램* 은 그렇게 쉬운 프로그램이 아니다.<br>
스택(stack)의 자료구조를 사용하면 그나마 좀 쉬워지지만<br>
스택을 사용하지 않고 계산기 프로그램을 만드는 것은 보통 어려운 일이 아니다.</font>

In [50]:
queue = []
len(queue)

0

In [51]:
class Queue:
    def __init__(self):
        self.Queue_item = []
        
    def Enqueue(self, x):
        self.Queue_item.append(x)
        return None
    
    def Dequeue(self):
        Queue_len = len(self.Queue_item)
        if Queue_len == 0:
            print("Queue is empty!")
            return False
        
        result = self.Queue_item[0]
        del self.Queue_item[0]
        return result
    
    def isEmpty(self):
        return not self.Queue_item

In [52]:
test = Queue()
print(test.Queue_item)

[]


In [53]:
test.Enqueue(1)
print(test.Queue_item)
print(test.Dequeue())

[1]
1


In [54]:
test.Enqueue(2)
test.Enqueue(3)
test.Enqueue(4)
test.Enqueue(5)

In [74]:
print(test.Queue_item)
print(test.Dequeue())
print(test.Dequeue())
print(test.Dequeue())
print(test.Dequeue())
print(test.Dequeue())

[1]
1
Queue is empty!
False
Queue is empty!
False
Queue is empty!
False
Queue is empty!
False


In [60]:
test.Queue_item

[]

In [61]:
test.Enqueue(1)

In [70]:
test.Queue_item

[1]

In [72]:
test.Queue_item and 0

0

In [75]:
print(test.isEmpty())

True


In [1]:
import numpy as np

In [2]:
a = np.array([1,2])
print(a.shape)

(2,)


In [4]:
b = np.array([[1],[2]])
print(b.shape)

(2, 1)


In [5]:
print(f"dimension of a : {a.ndim}, and that of b : {b.ndim}")

dimension of a : 1, and that of b : 2


In [6]:
A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [9]:
C = np.dot(A,b)

In [11]:
C.shape
print(C)

[[ 5]
 [11]
 [17]]


In [13]:
D = np.dot(A, a)

In [15]:
D.shape
print(D)

[ 5 11 17]


In [17]:
x = np.zeros((60000,784))

In [20]:
x_batch = x[0:100]

In [22]:
x_batch.shape

(100, 784)

In [23]:
delta = 1e-7

In [30]:
delta * 10000000

1.0

In [31]:
2 / 100

0.02

In [32]:
x_train = np.zeros((60000, 784))

In [34]:
train_size = x_train.shape[0]
batch_size = 10

In [35]:
batch_mask = np.random.choice(train_size, batch_size)

In [36]:
batch_mask

array([54679, 15323,  9966, 28419,  7655, 27044, 10489, 53799, 16507,
       38781])

In [94]:
np.random.choice(3,2, replace=False)

array([1, 0])

In [95]:
a = np.array([1,2,3,4,5,6,7])
print(a.ndim)

1


In [96]:
a.shape

(7,)

In [97]:
a.size

7

In [102]:
a = np.arange(10).reshape(2,5)

In [103]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.sum(a)

45

In [105]:
a = np.zeros((100,10))

In [107]:
a[np.arange(100), 5] = 1

In [108]:
a

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 

In [109]:
t = [[0,1,2,3,4,5,6,7,8,9]]

In [111]:
t[0]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [120]:
t = [0,0,0,0,0,0,0,0,0,0]
a = []
for i in range(10):
    t[i] = i
    a.append(t)
    t = [0,0,0,0,0,0,0,0,0,0]

AttributeError: 'list' object has no attribute 'shape'

In [123]:
a_cp = a[:]
print(a_cp)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 3, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 4, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 5, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 6, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 7, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 8, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]]


In [125]:
for _ in range(10):
    for que in a:
        a_cp.append(que)

In [128]:
t = np.array(a_cp)

In [135]:
t.shape

(110, 10)

In [142]:
t = t[:100][:]

In [168]:
(t[:10])[2][2]

2

In [159]:
t[[1,2,3,4,5],[1,1,2,2,5]] # ===> 이를 해석하면, [t[1,1], t[2,1], t[3,2], t[4,2], t[5,5]]인 넘파이 배열을 생성한다.

array([1, 0, 0, 0, 5])

In [172]:
np.array([t[1,1], t[2,1], t[3,2], t[4,2], t[5,5]])

array([1, 0, 0, 0, 5])

In [161]:
t[1:6][1,1,2,2,5] # 이런 식으로는 배열을 내려가면서 내가 원하는 인덱스들을 뽑아낼 수 없어. Arr[][] 이 표기법은 불가능 # for 문을 써야 돼 이렇게 쓰려면
# 따라서 Arr[[1,2,3,4,5],[1,1,2,2,5]] 이런 식으로 NumPy배열을 다뤄야 해!!

IndexError: too many indices for array

In [171]:
t[1:6]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0]])

In [190]:
np.float32(1e-45)

1e-45

In [191]:
max(100, 1)

100

In [ ]:
32 